git:
  depth: 1
  quiet: true

matrix:
  include:
    - {name: "Ubuntu 14.04 Qt5", os: "linux", dist: "trusty",  env: "QT5_BUILD=ON",   compiler: "gcc", addons: {apt: {packages: "qtbase5-dev qttools5-dev qttools5-dev-tools"}}}
    - {name: "Ubuntu 14.04 Qt4", os: "linux", dist: "trusty",  env: "QT5_BUILD=OFF",  compiler: "gcc", addons: {apt: {packages: "libqt4-dev libqjson-dev"}}}
    - {name: "Ubuntu 16.04 Qt5", os: "linux", dist: "xenial",  env: "QT5_BUILD=ON",   compiler: "gcc", addons: {apt: {packages: "qtbase5-dev qttools5-dev qttools5-dev-tools"}}}
    - {name: "Ubuntu 16.04 Qt4", os: "linux", dist: "xenial",  env: "QT5_BUILD=OFF",  compiler: "gcc", addons: {apt: {packages: "libqt4-dev libqjson-dev"}}}
    - {name: "macOS", os: "osx", addons: {homebrew: {packages: "qt5", casks: "sparkle"}}}

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DCMAKE_BUILD_TYPE=Debug         \
            -DQT5_BUILD=$QT5_BUILD
      cmake --build .
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DCMAKE_BUILD_TYPE=Debug         \
            -DCMAKE_PREFIX_PATH=$(brew cask info sparkle | grep /usr/local/Caskroom | cut -d' ' -f 1)\;$(brew --prefix qt5)
      cmake --build .
    fi
