name: Build with CMake and Qt5

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default cmake qtbase5-dev qt5-qmake

    - name: Build project
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DQT5_BUILD=ON ..
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: build  # Change this path to the directory where your artifacts are generated
